
#ifndef __fagexSingleton_h__
#define __fagexSingleton_h__

#include "fagexStdHeaders.h"

// Turn off warnings generated by this singleton implementation
#pragma warning (disable : 4311)
#pragma warning (disable : 4312)

namespace fagex {

	template <typename T> class Singleton
	{
	protected:
		static T* ms_Singleton;

	public:
		Singleton(void)
		{
			assert(!ms_Singleton);
			ms_Singleton = static_cast< T* >(this);
		}

		~Singleton(void)
		{  
			assert(ms_Singleton);  
			ms_Singleton = 0; 
		}

		static T& getSingleton(void)
		{	
			assert(ms_Singleton);  
			return (*ms_Singleton); 
		}

		static T* getSingletonPtr(void)
		{ 
			return ms_Singleton; 
		}
	};
}
#endif //__fagexSingleton_h__