[LOGSERVICE]
ProcessDir=$HOME$logservice
ProcessFileName=logservice
ProcessParams=logservice.conf
ServerProcess=1
StartSleep=1

[UNIQUENAMED]
ProcessDir=$HOME$uniquenamed
ProcessFileName=uniquenamed
ProcessParams=gamesys.conf
ProcessKill=pkill -9 uniquenamed
ServerProcess=1
StartSleep=2

[GAUTHD]
ProcessDir=$HOME$gauthd/
ProcessFileName=gauthd
ProcessStart=./gauthd
ProcessKill=pkill -9 gauthd
ServerProcess=1
StartSleep=3

[GAMEDBD]
ProcessDir=$HOME$gamedbd
ProcessFileName=gamedbd
ProcessParams=gamesys.conf
ProcessKill=pkill -9 gamedbd
ServerProcess=1
StartSleep=10

[GACD]
ProcessDir=$HOME$gacd
ProcessFileName=gacd
ProcessParams=gamesys.conf
ServerProcess=1
StartSleep=3
StopSleep=1

[GFACTIOND]
ProcessDir=$HOME$gfactiond
ProcessFileName=gfactiond
ProcessParams=gamesys.conf
ServerProcess=1
StartSleep=4
StopSleep=1

[GDELIVERYD]
ProcessDir=$HOME$gdeliveryd
ProcessFileName=gdeliveryd
ProcessParams=gamesys.conf
ServerProcess=1
StartSleep=4
StopSleep=5

[GLINKD 1]
ProcessDir=$HOME$glinkd
ProcessFileName=glinkd
ProcessParams=gamesys.conf 1
ServerProcess=1
StartSleep=1
StopSleep=10

[GLINKD 2]
ProcessDir=$HOME$glinkd
ProcessFileName=glinkd
ProcessParams=gamesys.conf 2
ServerProcess=1
StartSleep=1

[GLINKD 3]
ProcessDir=$HOME$glinkd
ProcessFileName=glinkd
ProcessParams=gamesys.conf 3
ServerProcess=1
StartSleep=1

#[GLINKD 4]
#ProcessDir=$HOME$glinkd
#ProcessFileName=glinkd
#ProcessParams=gamesys.conf 4
#ServerProcess=1
