[GAuthServer]
host = 127.0.0.1
port = 29200

#Allowed auth type, separated by space
#login - by login and password
#token - by password hash, require add or set token_login_support = true in gdeliveryd gamesys.conf
#Default value : login token
allow_auth_type = login

#Timeout to check table usecashnow for gold request in seconds
#Default value : 5
gold_timeout = 5

#Password hash type
#1 - base64 - base64_encode(md5($Login.$Pass, true))
#2 - md5 - "0x".md5($Login.$Pass)
hash_type = 1

#Some debug information will be output
debug_mode=false

[Mysql]
#MySQL database setup requisites
host = 127.0.0.1
port = 3306
user = root
pass = root
db = pw

[Validator]
#Validate login and token for forbidden symbols by regex
is_enabled = true
#With default value allowed: all english and russian letters, all numbers, dot, @, -, _
#Default value : ^[а-яА-Яa-zA-Z0-9_\-@.]+$
#regex = ^[a-zA-Z0-9_\-$#@.]+$
#regex=^[a-zA-Z0-9_]+$
regex=^[a-zA-Z0-9._@\-а-яА-ЯёЁ]+$

[Antibrut]
#It work like $count login try for $interval seconds = block auth for $block_time
is_enabled = true
count = 3
interval = 10
block_time = 60

[Secure]
#If all 4 parameters are set, traffic encryption will be performed using the RC4 protocol
#isec    = 2
#iseckey = baxiykbpn3fxLqpsdpiodI4iazqjdl
#osec    = 2
#oseckey = baxixD0awqydOtrxjxr8uhzaslmnqh
